name: Dependabot Security Check

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  security:
    name: Security Audit
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Security Audit (for Node.js)
        run: |
          npm install --package-lock-only
          npm audit --audit-level=critical || exit 1
